name: "ColonyWars"
version: "${project.version}"
main: "com.ithinkrok.cw.CWPlugin"
author: "ithinkrok"
database: true

permissions:
  mccw.admin:
    default: "op"
    description: "Gives all admin command permissions"
    children:
      mccw.gamestate: true
      mccw.cw: true
  mccw.gamestate:
    description: "Allows use of the /gamestate command"
    default: false
  mccw.cw:
    description: "Allows use of all subcommands of /cw"
    default: false
    children:
      mccw.cw.money: true
      mccw.cw.building: true
      mccw.cw.team: true
      mccw.cw.custom: true
  mccw.cw.money:
    description: "Allows use of /cw money"
    default: false
  mccw.cw.building:
    description: "Allows use of /cw building"
    default: false
  mccw.cw.team:
    description: "Allows use of /cw team"
    default: false
  mccw.cw.custom:
    description: "Allows use of /cw custom"
    default: false

commands:
  gamestate:
    description: "Changes the GameState of the current GameGroup"
    aliases: ["gs", "gstate"]
    permission: "mccw.gamestate"
    usage: "/<command> <gamestate>"
  colonywars:
    description: "Various CW testing utils"
    aliases: ["cw", "cwars", "wars"]
    usage: "/<command> <subcommand> [sub command args...]"