name: "ColonyWars"
version: "${project.version}"
main: "com.ithinkrok.mccw.WarsPlugin"
author: "ithinkrok"
depend: ["HologramAPI", "ProtocolLib"]
permissions:
  mccw.*:
    description: "Gives access to all MCCW commands"
    children:
      mccw.test: true
      mccw.gamestate: true
      mccw.members: true
    default: "op"
  mccw.test:
    description: "Allows use of the test command"
  mccw.gamestate:
    description: "Allows use of the gamestate command"
  mccw.members:
    description: "allows use of the members command"
    default: true
commands:
  transfer:
    description: "Transfers money from your account to your team's account"
    aliases: ["t", "tf"]
    usage: "/transfer [money]"
  test:
    description: "ColonyWars test command"
    usage: "/test <test> [test arguments...]"
    permission: "mccw.test"
  gamestate:
    description: "Changes the game state"
    aliases: ["gs"]
    usage: "/gamestate <newstate>"
    permission: "mccw.gamestate"
  members:
    description: "Lists the members of your team"
    aliases: ["mbrs", "players", "team", "plrs", "classes"]
    usage: "/members"
    permission: "mccw.members"