name: "ColonyWars"
version: "${project.version}"
main: "com.ithinkrok.cw.CWPlugin"
author: "ithinkrok"
depend: ["MinigamesBase"]
database: true

permissions:
  mccw.admin:
    default: "op"
    description: "Gives all admin command permissions"
    children:
      mccw.cw: true
      mccw.tmm.others: true
      mccw.members.others: true
      mccw.fix.others: true
      mccw.teamchat.others: true
      mccw.transfer.others: true
      mccw.spawn.others: true
  mccw.user:
    default: true
    description: "Gives all user command permission"
    children:
      mccw.tmm: true
      mccw.stats: true
      mccw.teamchat: true
      mccw.transfer: true
      mccw.fix: true
      mccw.leaderboard: true
      mccw.list: true
      mccw.members: true
      mccw.spawn: true
  mccw.cw:
    description: "Allows use of all subcommands of /cw"
    default: false
    children:
      mccw.cw.command: true
      mccw.cw.money: true
      mccw.cw.building: true
      mccw.cw.team: true
      mccw.cw.custom: true
      mccw.cw.level: true
      mccw.cw.kit: true
      mccw.cw.rejoin: true
  mccw.cw.command:
    description: "Makes the /cw command usable"
    default: false
  mccw.cw.money:
    description: "Allows use of /cw money"
    default: false
  mccw.cw.building:
    description: "Allows use of /cw building"
    default: false
  mccw.cw.team:
    description: "Allows use of /cw team"
    default: false
  mccw.cw.custom:
    description: "Allows use of /cw custom"
    default: false
  mccw.cw.level:
    description: "Allows use of /cw level"
    default: false
  mccw.cw.kit:
    description: "Allows use of /cw kit"
    default: false
  mccw.cw.rejoin:
    description: "Allows use of /cw rejoin"
    default: false
  mccw.tmm:
    description: "Allows use of /tmm"
    default: false
  mccw.tmm.others:
    description: "Allows changing of money message status for others"
    default: false
  mccw.stats:
    description: "Allows use of /stats"
    default: false
  mccw.teamchat:
    description: "Allows use of /teamchat"
    default: false
  mccw.teamchat.others:
    description: "Allows use of /teamchat on other teams"
    default: false
  mccw.transfer:
    description: "Allows use of /transfer"
    default: false
  mccw.transfer.others:
    description: "Allows using /transfer as other players"
    default: false
  mccw.fix:
    description: "Allows use of /fix"
    default: false
  mccw.fix.others:
    description: "Allows use of /fix on other players"
    default: false
  mccw.leaderboard:
    description: "Allows use of /leaderboard"
    default: false
  mccw.list:
    description: "Allows use of /list"
    default: false
  mccw.members:
    description: "Allows use of /members"
    default: false
  mccw.members.others:
    description: "Allows use of /members for other teams"
    default: false
  mccw.kill:
    description: "Shows the defunct kill command in player /help command lists"
    default: false
  mccw.spawn:
    description: "Allows use of /spawn"
    default: false
  mccw.spawn.others:
    description: "Allows use of /spawn for other players"
    default: false