additional_configs:
  - "colony_wars/config/base.yml"

maps:
  lobby: "colony_wars/maps/lobby.yml"
  12canyon: "colony_wars/maps/12canyon.yml"
  canyon: "colony_wars/maps/canyon.yml"
  cavern: "colony_wars/maps/cavern.yml"
  forest_hills: "colony_wars/maps/forest_hills.yml"
  hills_and_lakes: "colony_wars/maps/hills_and_lakes.yml"
  jungle_valley: "colony_wars/maps/jungle_valley.yml"
  jungle_mountain: "colony_wars/maps/jungle_mountain.yml"
  mega_taiga: "colony_wars/maps/mega_taiga.yml"
  mesa: "colony_wars/maps/mesa.yml"
  nether: "colony_wars/maps/nether.yml"
  oasis: "colony_wars/maps/oasis.yml"
  snow_hills: "colony_wars/maps/snow_hills.yml"
  fort: "colony_wars/maps/fort.yml"
  slavic: "colony_wars/maps/slavic.yml"

# Specifies identifiers for teams to be created
team_identifiers:
  red:
    dye_color: RED
  blue:
    dye_color: BLUE

# Specifies default shared objects. Some shared objects are required by certain Java Classes used in the game.
shared_objects:
  start_info:
    game_state: "lobby"
  game:
    max_players: 40
    default_motd: "Colony wars yay"
    chat_prefix: "&7[&3ColonyWars&7] &e"
  map_scoreboard:
    votable_maps: &votable_maps
      - "canyon"
      - "forest_hills"
      - "cavern"
      - "hills_and_lakes"
      - "jungle_valley"
      - "oasis"
      - "snow_hills"
      - "jungle_mountain"
      - "mega_taiga"
      - "12canyon"
      - "mesa"
      - "fort"
      - "slavic"
      - "random"


game_states:
  lobby:
    listeners:
      main:
        class: "com.ithinkrok.minigames.util.gamestate.SimpleLobbyListener"
        config:
          start_countdown:
            name: "start"
            locale_stub: "countdowns.start"
            min_players: 2
            needs_more_players_locale: "countdowns.start.needs_more_players"
            seconds: 181

          next_gamestate: "game"
          lobby_map: "lobby"
          give_on_join:
            clear_inventory: true
            custom_items:
              - name: "map_voter"
                slot: 0
              - name: "team_chooser"
                slot: 1
              - name: "class_chooser"
                slot: 2
              - name: "hub_returner"
                slot: 8

  game:
    listeners:
      setup:
        class: "com.ithinkrok.cw.gamestate.CWGameStartListener"
        config:
          map_voting:
            random_map: "random"
            map_list: *votable_maps
          choosable_teams: &choosable_teams
            - "red"
            - "blue"
          choosable_kits: &choosable_kits
            - "general"
            - "scout"
            - "cloaker"
            - "peasant"
            - "dark_knight"
            - "mage"
            - "archer"
            - "warrior"
            - "priest"
            - "inferno"
            - "vampire"
            - "engineer"
          start_items:
            clear_inventory: true
            custom_items:
              - name: "pickaxe"
                slot: 0
      main:
        class: "com.ithinkrok.cw.gamestate.CWInGameListener"
        config: &base_game_config
          gold_shared_object: "gold_config"
          buildings:
            destroy_wait: 3
          showdown_start:
            teams: 2
            players: 4
          spectator_items:
            clear_inventory: true
            custom_items:
              - name: "spectate_chooser"
                slot: 0
              - name: "invisible_user_toggle"
                slot: 1
              - name: "hub_returner"
                slot: 8
          ender_amount: "6000+ranInt(9)*3000"
  showdown:
    listeners:
      main:
        class: "com.ithinkrok.cw.gamestate.CWShowdownInGameListener"
        config: *base_game_config
  aftermath:
    listeners:
      aftermath:
        class: "com.ithinkrok.minigames.util.gamestate.SimpleAftermathListener"

# Lobby custom items only
custom_items:
  map_voter:
    display_name_locale: "map_voter.name"
    description_locale: "map.voter.desc"
    material: "EMPTY_MAP"
    listeners:
      vote:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.util.item.MapVoter"
        config:
          votable_maps: *votable_maps
          map_material: "EMPTY_MAP"
  team_chooser:
    display_name_locale: "team_chooser.name"
    description_locale: "team_chooser.desc"
    material: "LEATHER_HELMET"
    listeners:
      choose:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.util.item.TeamChooser"
        config:
          choosable_teams: *choosable_teams
          chooser_material: "WOOL"
  class_chooser:
    display_name_locale: "kit_chooser.name"
    description_locale: "kit_chooser.desc"
    material: "WOOD_SWORD"
    listeners:
      choose:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.util.item.KitChooser"
        config:
          choosable_kits: *choosable_kits