
additional_configs:
  - "colony_wars/config/base.yml"

lang_files:
#  - "cw_tutorial/lang/cw_tutorial.lang"
#  - "cw_tutorial/lang/items.lang"

maps:
  lobby: "colony_wars/maps/lobby.yml"
  old_lobby: "colony_wars/maps/old_lobby.yml"
  12canyon: "colony_wars/maps/12canyon.yml"
  canyon: "colony_wars/maps/canyon.yml"
  cavern: "colony_wars/maps/cavern.yml"
  forest_hills: "colony_wars/maps/forest_hills.yml"
  hills_and_lakes: "colony_wars/maps/hills_and_lakes.yml"
  jungle_valley: "colony_wars/maps/jungle_valley.yml"
  jungle_mountain: "colony_wars/maps/jungle_mountain.yml"
  mega_taiga: "colony_wars/maps/mega_taiga.yml"
  mesa: "colony_wars/maps/mesa.yml"
  nether: "colony_wars/maps/nether.yml"
  oasis: "colony_wars/maps/oasis.yml"
  snow_hills: "colony_wars/maps/snow_hills.yml"
  fort: "colony_wars/maps/fort.yml"
  slavic: "colony_wars/maps/slavic.yml"

team_identifiers:
  red:
    dye_color: RED
  blue:
    dye_color: BLUE
  green:
    dye_color: GREEN
  yellow:
    dye_color: YELLOW

shared_objects:
  game:
    max_players: 8
    default_motd: "Colony wars tutorial"
    chat_prefix: "&7[&3ColonyWars&7] &e"
    accredited: false
  start_info:
    game_state: "tutorial"
    map: "#param1"
    backup_map: "canyon"
  map_scoreboard:
    votable_maps: &votable_maps
      - "disable"

game_states:
  tutorial:
    listeners:
      setup:
        class: "com.ithinkrok.cw.gamestate.CWGameStartListener"
        config:
          map_voting:
            random_map: "random"
            map_list: *votable_maps
          choosable_teams: &choosable_teams
            - "red"
            - "blue"
            - "green"
            - "yellow"
          choosable_kits: &choosable_kits
            - "general"
            - "scout"
            - "cloaker"
            - "peasant"
            - "dark_knight"
            - "mage"
            - "archer"
            - "warrior"
            - "priest"
            - "inferno"
            - "vampire"
            - "engineer"
          start_items:
            clear_inventory: true
            custom_items:
              - name: "pickaxe"
                slot: 0
            books:
              - name: "handbook"
                slot: 8
      main:
        class: "com.ithinkrok.cw.gamestate.CWTutorialGameListener"
        config: &base_game_config
          gold_shared_object: "gold_config"
          buildings:
            destroy_wait: 3
          showdown_start:
            teams: -1
            players: -1
          spectator_items:
            clear_inventory: true
            custom_items:
              - name: "spectate_chooser"
                slot: 0
              - name: "invisible_user_toggle"
                slot: 1
          ender_amount: "6000+ranInt(9)*3000"
          blood_effect:
            effect: "reddust"
            r: 1
            g: 0
            b: 0

custom_items:
  map_voter:
    display_name_locale: "map_voter.name"
    description_locale: "map.voter.desc"
    material: "EMPTY_MAP"
    listeners:
      vote:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.util.item.MapVoter"
        config:
          votable_maps: *votable_maps
          map_material: "EMPTY_MAP"
  invisible_user_toggle:
    display_name_locale: "invisible_user_toggle.name"
    material: "STRING"
    listeners:
      invisible_user_toggle:
        class: "com.ithinkrok.minigames.util.item.InvisibleUserToggle"
        events: ["rightClick"]
  spectate_chooser:
    display_name_locale: "spectate_chooser.name"
    material: "SKULL_ITEM"
    durability: 3
    listeners:
      spectate_chooser:
        class: "com.ithinkrok.minigames.util.item.SpectateChooser"
        events: ["rightClick"]