folder: "mccw_canyon"
description: "A canyon separates the four teams bases..."
environment: normal
enable_weather: false

shared_objects:
  showdown:
    center:
      x: -178
      y: 95
      z: 183
    size:
      x: 30
      z: 30
  spawn_locations:
    blue:
      x: 8
      y: 95
      z: -1
    green:
      x: 7
      y: 95
      z: 369
    yellow:
      x: -363
      y: 95
      z: 368
    red:
      x: -362
      y: 95
      z: -2

listeners:
  initial_buildings:
    class: "com.ithinkrok.cw.map.InitialBuildingSpawner"
    config:
      initial_buildings:
        - building: "Base"
          team: "blue"
          location:
            x: 9
            y: 94
            z: -2
        - building: "Base"
          team: "green"
          location:
            x: 8
            y: 94
            z: 370
        - building: "Base"
          team: "yellow"
          location:
            x: -364
            y: 94
            z: 369
        - building: "Base"
          team: "red"
          location:
            x: -363
            y: 94
            z: -3
