folder: "mccw_lobby"
description: "The lobby map for MCCW"
environment: "normal"

lang_files:
  - "colony_wars/lang/lobby.lang"

spawn:
  x: 459.5
  y: 66.1
  z: -456.6
  yaw: 180
  pitch: 0

listeners:
  spleef:
    class: "com.ithinkrok.minigames.util.lobbygames.SpleefMinigame"
    config:
      arenas:
        arena1:
          queue_buttons:
            - x: 535
              y: 56
              z: -497
          spawn_locations:
            - x: 548.5
              y: 52.5
              z: -481.5
            - x: 526.5
              y: 52.5
              z: -480.5
          exit_location:
            x: 522
            y: 56
            z: -481
          snow:
            min:
              x: 525
              y: 51
              z: -493
            max:
              x: 549
              y: 51
              z: -471
          extra_radius: 3
      spade: "IRON_SPADE"
  parkour:
    class: "com.ithinkrok.cw.lobbygames.ParkourMinigame"
    config:
      max_parkour_money: 6001
      runs:
        - x: 521
          y: 92
          z: -478
          reward: 1000
        - x: 425
          y: 70
          z: -434
          reward: 3000
  wool:
    class: "com.ithinkrok.minigames.util.lobbygames.WoolMinigame"