folder: "mccw_mesa"
description: "Mesa like map, aided by senseioli!"
environment: normal
enable_weather: false

shared_objects:
  showdown:
    center:
      x: 0
      y: 81
      z: 0
    size:
      x: 30
      z: 30
  spawn_locations:
    red:
      x: 199.5
      y: 66
      z: 199.5
    blue:
      x: -198.5
      y: 66
      z: -198.5
    yellow:
      x: -198.5
      y: 66
      z: 199.5
    green:
      x: 199.5
      y: 66
      z: -198.5

listeners:
  initial_buildings:
    class: "com.ithinkrok.cw.map.InitialBuildingSpawner"
    config:
      initial_buildings:
        - building: "Base"
          team: "red"
          location:
            x: 200
            y: 65
            z: 200
        - building: "Base"
          team: "blue"
          location:
            x: -200
            y: 65
            z: -200
        - building: "Base"
          team: "yellow"
          location:
            x: -200
            y: 65
            z: 200
        - building: "Base"
          team: "green"
          location:
            x: 200
            y: 65
            z: -200
