folder: "mccw_oasis"
description: "A desert oasis"
environment: normal
enable_weather: false

shared_objects:
  showdown:
    center:
      x: 8
      y: 33
      z: -34
    size:
      x: 30
      z: 30
  spawn_locations:
    red:
      x: -263.5
      y: 38
      z: 237.5
    yellow:
      x: -262.5
      y: 38
      z: -305.5
    blue:
      x: 280.5
      y: 38
      z: -304.5
    green:
      x: 279.5
      y: 38
      z: 238.5

listeners:
  initial_buildings:
    class: "com.ithinkrok.cw.map.InitialBuildingSpawner"
    config:
      initial_buildings:
        - building: "Base"
          team: "red"
          location:
            x: -265
            y: 37
            z: 238
        - building: "Base"
          team: "yellow"
          location:
            x: -264
            y: 37
            z: -307
        - building: "Base"
          team: "blue"
          location:
            x: 281
            y: 37
            z: -306
        - building: "Base"
          team: "green"
          location:
            x: 280
            y: 37
            z: 239
