folder: "mccw_oldlobby"
description: "The old lobby map for MCCW"
environment: "normal"
enable_weather: false
enable_time: false

lang_files:
  - "colony_wars/lang/lobby.lang"

listeners:
  spleef:
    class: "com.ithinkrok.minigames.util.lobbygames.SpleefMinigame"
    config:
      arenas:
        arena1:
          queue_buttons:
            - x: 312
              y: 64
              z: 34
            - x: 328
              y: 64
              z: 34
          spawn_locations:
            - x: 325.5
              y: 65
              z: 34.5
            - x: 315.5
              y: 65
              z: 34.5
          exit_location:
            x: 320
            y: 65
            z: 42
          snow:
            min:
              x: 315
              y: 63
              z: 29
            max:
              x: 325
              y: 63
              z: 39
          extra_radius: 3
      spade: "IRON_SPADE"
  parkour:
    class: "com.ithinkrok.cw.lobbygames.ParkourMinigame"
    config:
      max_parkour_money: 6001
      runs:
        - x: 349
          y: 84
          z: 6
          reward: 500
        - x: 426
          y: 74
          z: 100
          reward: 1200
        - x: 425
          y: 74
          z: 100
          reward: 1200
        - x: 286
          y: 76
          z: 106
          reward: 3000
  wool:
    class: "com.ithinkrok.minigames.util.lobbygames.WoolMinigame"