folder: "mccw_slavic"
description: "Slavic map"
credit.0: "&7Created by &4IvanZvania"
environment: normal
enable_weather: false

shared_objects:
  showdown:
    center:
      x: 3
      y: 42
      z: 4
    size:
      x: 25
      z: 25
  spawn_locations:
    blue:
      x: 147
      y: 41
      z: -140
    green:
      x: -141
      y: 42
      z: 148
    yellow:
      x: -141
      y: 42
      z: -140
    red:
      x: 147
      y: 42
      z: 148

listeners:
  initial_buildings:
    class: "com.ithinkrok.cw.map.InitialBuildingSpawner"
    config:
      initial_buildings:
        - building: "Base"
          team: "blue"
          location:
            x: 148
            y: 41
            z: -141
        - building: "Base"
          team: "green"
          location:
            x: -142
            y: 41
            z: 149
        - building: "Base"
          team: "yellow"
          location:
            x: -142
            y: 41
            z: -141
        - building: "Base"
          team: "red"
          location:
            x: 148
            y: 41
            z: 149
