folder: "mccw_snow_hills"
description: "Snowy hills. What more were you expecting?!"
environment: normal
enable_weather: false

shared_objects:
  showdown:
    center:
      x: 0
      y: 76
      z: 0
    size:
      x: 30
      z: 30
  spawn_locations:
    green:
      x: 199.5
      y: 85
      z: -198.5
    yellow:
      x: -198.5
      y: 85
      z: 199.5
    red:
      x: 199.5
      y: 85
      z: 199.5
    blue:
      x: -198.5
      y: 85
      z: -198.5

listeners:
  initial_buildings:
    class: "com.ithinkrok.cw.map.InitialBuildingSpawner"
    config:
      initial_buildings:
        - building: "Base"
          team: "green"
          location:
            x: 200
            y: 84
            z: -200
        - building: "Base"
          team: "yellow"
          location:
            x: -200
            y: 84
            z: 200
        - building: "Base"
          team: "red"
          location:
            x: 200
            y: 84
            z: 200
        - building: "Base"
          team: "blue"
          location:
            x: -200
            y: 84
            z: -200
