# The language files that will be used by default
lang_files:
  - "colony_wars/lang/colony_wars.lang"
  - "colony_wars/lang/weapon_modifier.lang"
  - "colony_wars/lang/items.lang"
  - "colony_wars/lang/commands.lang"

pre_configs:
  - "global/global.yml"

additional_configs:
  - "colony_wars/config/schematics.yml"
  - "colony_wars/config/custom_items.yml"
  - "colony_wars/config/kits.yml"

books:
  handbook: "colony_wars/books/handbook.json"

shared_objects:
  shop:
    items:
      - class: "com.ithinkrok.minigames.util.inventory.Upgradable"
        config:
          item: "EMPTY_MAP"
          upgrade_name: "@mg#vote_weight"
          upgrade_display_locale: "vote_weight.upgrade"
          max_level: 2
          cost: "10000*pow(10, @mg#vote_weight)"
          currency: "token_copper"
          purchase_locale: "vote_weight.buy"
      - class: "com.ithinkrok.minigames.util.inventory.Upgradable"
        config:
          item: "GOLD_INGOT"
          upgrade_name: "@global#gold_bonus"
          upgrade_display_locale: "double_gold.upgrade"
          max_level: 1
          cost: "2500*pow(2, @global#gold_bonus)"
          currency: "token_copper"
          broadcast_locale: "double_gold.buy"
      - class: "com.ithinkrok.minigames.util.inventory.Upgradable"
        config:
          item: "GOLD_INGOT"
          upgrade_name: "@global#gold_bonus"
          upgrade_display_locale: "triple_gold.upgrade"
          min_level: 2
          max_level: 2
          cost: "2500*pow(2, @global#gold_bonus)"
          currency: "token_copper"
          broadcast_locale: "triple_gold.buy"
      - class: "com.ithinkrok.minigames.util.inventory.SubInventory"
        display: "prismarine"
        config:
          name_locale: "building.invalid_loc"
  potion_strength_metadata:
    base_modifier: 1.0
    max_modifier: 1.0
    min_modifier: 0.5
    loss_on_potion: 0.05
    update_interval: 0.5 #seconds
    gain_per_second: 0.10
  schematic_options:
    progress_hologram: true
    build_speed: 2
    center_block_material: "OBSIDIAN"
    replace_materials:
      BARRIER: "AIR"
      DIAMOND_ORE: "GOLD_ORE"
  showdown_metadata:
    min_radius: 5
    shrink_start_time: 180
    shrink_interval_time: 20
    shrink_start_locale: "showdown.shrinking"
# Required for User.java
  user:
    default_stats:
      max_health: 20
      health: 20
      food_level: 10
      saturation: 5
      fly_speed: 0.1
      walk_speed: 0.2
      max_hit_delay: 0.7
    use_new_combat: false
  user_money_metadata:
    remove_gamestate: "aftermath"
    add_locale: "money.balance.user.add"
    subtract_locale: "money.balance.user.subtract"
    new_locale: "money.balance.user.new"
  # Required for TeamMoney.java
  team_money_metadata:
    remove_gamestate: "aftermath"
    add_locale: "money.balance.team.add"
    subtract_locale: "money.balance.team.subtract"
    new_locale: "money.balance.team.new"
  # Required for CWScoreboardHandler.java
  colony_wars_scoreboard:
    title: "scoreboard.title"
    user_balance: "scoreboard.user_balance"
    team_balance: "scoreboard.team_balance"
    building_now_count: "scoreboard.building_now_count"
    revival_rate: "scoreboard.revival_rate"
  gold_config:
    ore_blocks:
      gold_ore: "GOLD_INGOT,6"
      quartz_ore: "GOLD_INGOT,6"
      diamond_ore: "DIAMOND,1"
    trees:
      enabled: true
      item_material: "GOLD_INGOT"
      item_amount: "1+x+(ln(x)/ln(1.5))-min(sqrt((pow(x,3))/500),pow(x,0.9))"
      log_materials:
        - "LOG"
        - "LOG_2"
    items:
      gold_ingot:
        user: 60
        team: 40
      diamond:
        user: 1200
        team: 800
    pickup_sound: "ENTITY_EXPERIENCE_ORB_PICKUP"

custom_entities:
  shopkeeper:
    type: "VILLAGER"
    baby: false
    name: "Shopkeeper"
    listeners:
      shop:
        class: "com.ithinkrok.minigames.util.inventory.MinigamesShop"

commands:
  colonywars:
    description: "Various CW testing utils"
    aliases: ["cw", "cwars", "wars"]
    permission: "mccw.cw.command"
    usage: "/<command> <subcommand> [sub command args...]"
    class: "com.ithinkrok.cw.command.CWCommand"
  togglemoneymessage:
    description: "Toggles money message status"
    aliases: ["tmm"]
    permission: "mccw.tmm"
    usage: "/<command> [newstatus]"
    class: "com.ithinkrok.cw.command.ToggleMoneyMessageCommand"
  stats:
    description: "Shows your stats"
    permission: "mccw.stats"
    usage: "/<command> [category]"
    class: "com.ithinkrok.cw.command.StatsCommand"
    tab:
      - pattern: "*"
      #TODO gsm can send lists of tab complete groups (such as ggName) to clients
        values: ["ithinkrok", "#param2", "#ggName", "#ggType", "#gsmPlayer", "#gsmPlayer:this", "#gsmGame"]

  teamchat:
    description: "Allows you to chat privately to your team"
    aliases: ["tc", "tchat", "teamc"]
    permission: "mccw.teamchat"
    usage: "/<command>"
    class: "com.ithinkrok.cw.command.TeamChatCommand"
  deposit:
    description: "Deposit money into your team's account"
    aliases: ["transfer", "t", "tf"]
    permission: "mccw.transfer"
    usage: "/<command> <amount>"
    class: "com.ithinkrok.cw.command.TransferCommand"
    config:
      default_target: "team"
  share:
    description: "Share money with your team members"
    permission: "mccw.transfer"
    usage: "/<command> <amount> [player]"
    class: "com.ithinkrok.cw.command.TransferCommand"
    config:
      default_target: "all"
  fix:
    description: "Fixes you if you are stuck"
    aliases: ["unstuck", "fixme"]
    permission: "mccw.fix"
    usage: "/<command>"
    class: "com.ithinkrok.cw.command.FixCommand"
  leaderboard:
    description: "Shows a leaderboard of the top players"
    aliases: ["lb", "leaders", "lboard", "top"]
    permission: "mccw.leaderboard"
    usage: "/<command> [amount] [category]"
    class: "com.ithinkrok.cw.command.LeaderboardCommand"
  list:
    description: "Lists who is in the minigame"
    aliases: ["ls"]
    permission: "mccw.list"
    usage: "/<command>"
    class: "com.ithinkrok.cw.command.ListCommand"
  members:
    description: "Shows the members of your team"
    aliases: ["team", "mbrs"]
    permission: "mccw.members"
    usage: "/<command>"
    class: "com.ithinkrok.cw.command.MembersCommand"
  spawn:
    description: "Teleports you to the lobby spawn"
    aliases: ["spwn", "home"]
    permission: "mccw.spawn"
    others_permission: "mccw.spawn.others"
    usage: "/<command>"
    class: "com.ithinkrok.cw.command.SpawnCommand"

listeners:
  global_cw:
    class: "com.ithinkrok.cw.listener.GlobalCWListener"